export const NIFTY_50_SYMBOLS = [
  { symbol: 'RELIANCE.NS', name: 'Reliance Industries' },
  { symbol: 'TCS.NS', name: 'Tata Consultancy Services' },
  { symbol: 'HDFCBANK.NS', name: 'HDFC Bank' },
  { symbol: 'INFY.NS', name: 'Infosys' },
  { symbol: 'ICICIBANK.NS', name: 'ICICI Bank' },
  { symbol: 'HINDUNILVR.NS', name: 'Hindustan Unilever' },
  { symbol: 'SBIN.NS', name: 'State Bank of India' },
  { symbol: 'BHARTIARTL.NS', name: 'Bharti Airtel' },
  { symbol: 'ITC.NS', name: 'ITC' },
  { symbol: 'KOTAKBANK.NS', name: 'Kotak Mahindra Bank' },
  { symbol: 'LT.NS', name: 'Larsen & Toubro' },
  { symbol: 'HCLTECH.NS', name: 'HCL Technologies' },
  { symbol: 'AXISBANK.NS', name: 'Axis Bank' },
  { symbol: 'ASIANPAINT.NS', name: 'Asian Paints' },
  { symbol: 'MARUTI.NS', name: 'Maruti Suzuki' },
  { symbol: 'SUNPHARMA.NS', name: 'Sun Pharmaceutical' },
  { symbol: 'TITAN.NS', name: 'Titan Company' },
  { symbol: 'BAJFINANCE.NS', name: 'Bajaj Finance' },
  { symbol: 'DMART.NS', name: 'Avenue Supermarts' },
  { symbol: 'NTPC.NS', name: 'NTPC' },
  { symbol: 'TATAMOTORS.NS', name: 'Tata Motors' },
  { symbol: 'ONGC.NS', name: 'ONGC' },
  { symbol: 'NESTLEIND.NS', name: 'Nestle India' },
  { symbol: 'WIPRO.NS', name: 'Wipro' },
  { symbol: 'M&M.NS', name: 'Mahindra & Mahindra' },
  { symbol: 'ULTRACEMCO.NS', name: 'UltraTech Cement' },
  { symbol: 'POWERGRID.NS', name: 'Power Grid Corporation' },
  { symbol: 'ADANIENT.NS', name: 'Adani Enterprises' },
  { symbol: 'ADANIPORTS.NS', name: 'Adani Ports' },
  { symbol: 'JSWSTEEL.NS', name: 'JSW Steel' },
  { symbol: 'TATASTEEL.NS', name: 'Tata Steel' },
  { symbol: 'COALINDIA.NS', name: 'Coal India' },
  { symbol: 'BAJAJFINSV.NS', name: 'Bajaj Finserv' },
  { symbol: 'TECHM.NS', name: 'Tech Mahindra' },
  { symbol: 'HDFCLIFE.NS', name: 'HDFC Life Insurance' },
  { symbol: 'SBILIFE.NS', name: 'SBI Life Insurance' },
  { symbol: 'BRITANNIA.NS', name: 'Britannia Industries' },
  { symbol: 'GRASIM.NS', name: 'Grasim Industries' },
  { symbol: 'CIPLA.NS', name: 'Cipla' },
  { symbol: 'DIVISLAB.NS', name: 'Divi\'s Laboratories' },
  { symbol: 'DRREDDY.NS', name: 'Dr. Reddy\'s Laboratories' },
  { symbol: 'EICHERMOT.NS', name: 'Eicher Motors' },
  { symbol: 'APOLLOHOSP.NS', name: 'Apollo Hospitals' },
  { symbol: 'HEROMOTOCO.NS', name: 'Hero MotoCorp' },
  { symbol: 'INDUSINDBK.NS', name: 'IndusInd Bank' },
  { symbol: 'BPCL.NS', name: 'Bharat Petroleum' },
  { symbol: 'TATACONSUM.NS', name: 'Tata Consumer Products' },
  { symbol: 'HINDALCO.NS', name: 'Hindalco Industries' },
  { symbol: 'BAJAJ-AUTO.NS', name: 'Bajaj Auto' },
  { symbol: 'SHRIRAMFIN.NS', name: 'Shriram Finance' },
];

export const SECTOR_COLORS: Record<string, string> = {
  'Technology': '#6366f1',
  'Financial Services': '#22c55e',
  'Energy': '#f59e0b',
  'Healthcare': '#ec4899',
  'Consumer Defensive': '#8b5cf6',
  'Consumer Cyclical': '#14b8a6',
  'Industrials': '#f97316',
  'Basic Materials': '#64748b',
  'Communication Services': '#06b6d4',
  'Utilities': '#84cc16',
  'Real Estate': '#e11d48',
  'Other': '#71717a',
};
